// <auto-generated />
namespace ATPTennisStat.SQLServerData.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddConstraintsToCategoryUmpireSurface : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddConstraintsToCategoryUmpireSurface));
        
        string IMigrationMetadata.Id
        {
            get { return "201706041844173_Add Constraints To Category Umpire Surface"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
